# Movie.create(title: "The Room", synopsis: "This film centers on Johnny, a man who has it all; great friends, a good job, and a gorgeous fiancée named Lisa. But Lisa's innocent act masks the fact that she's looking to bring Johnny down, and her manipulations are tearing Johnny apart. As Lisa informs her cancer-ridden mother, Claudette, that Johnny hit her (and he did not hit her, that is bull$&*t, he did not!), Johnny's best friend, Mark, finds his resistance to Lisa's seductive charms weakening. Meanwhile, local orphan Denny looks up to Johnny, and needs the older man's help after the teen rips off a drug dealer. What kind of drugs? It doesn't matter. Then guys play football in tuxedos, because you can play football anywhere. This movie is seriously not to be missed.", poster_url: "http://content7.flixster.com/movie/10/89/91/10899157_det.jpg", potatometer: 33)

# Movie.create(title: "The Last Airbender", synopsis: "Suspense auteur M. Night Shyamalan takes a break from crafting original screenplays to tell this tale of a 12-year-old boy (Noah Ringer) who provides the last hope for restoring harmony to a land consumed by chaos. In a world balanced on the four nations of Water, Earth, Fire, and Air, people known as the Waterbenders, Earthbenders, Firebenders, and Airbenders have mastered their native elements. Though the masters can each manipulate their native elements, the only one with the power to manipulate all four elements is a young boy known as the Avatar. When the Avatar subsequently appears to die while still mastering his powers, the Fire nation launches a global war with the ultimate goal of global domination. One hundred years later, two teens discover that the Avatar and his flying bison have in fact been locked in suspended animation. Upon being freed from his prison, the Avatar embarks on an arduous quest to restore harmony among the four war-ravaged nations.", poster_url: "http://content7.flixster.com/movie/11/16/89/11168953_det.jpg", potatometer: 6)

# Movie.create(title: "Eternal Sunshine of the Spotless Mind", synopsis: "The second feature from director Michel Gondry (Human Nature) finds the filmmaker reteaming with screenwriter Charlie Kaufman for this off-the-wall romantic comedy. Jim Carrey stars as Joel Barish, a man who is informed that his ex-girlfriend Clementine (Kate Winslet) has had her memories of their relationship erased from her brain via an experimental procedure performed by Dr. Mierzwiak (Tom Wilkinson). Not to be outdone, Joel decides to have the same procedure done to himself. As Mierzwiak's bumbling underlings Stan (Mark Ruffalo) and Patrick (Elijah Wood) perform the operation on Joel -- over the course of an evening, in his apartment -- Joel struggles in his own mind to save the memories of Clementine from being deleted. Kirsten Dunst, David Cross, and Jane Adams also star.", poster_url: "http://content8.flixster.com/movie/55/05/71/5505718_det.jpg", potatometer: 93)

# Comment.create(text: "zomg this movie rocks", movie_id: 1, user_id: 1)

# Movie.create(title: "Showgirls", synopsis: "'I'm gonna dance,' Nomi Malone (Elizabeth Berkley) insists in the opening scene of Showgirls, and dance she does. In this quasi-update of All About Eve, Nomi is a drifter whose sole ambition is to headline the 'Goddess' topless dance show at the Stardust in Las Vegas. Of course, even Nomi must pay her dues, and she does so at the Cheetah, grinding poles and lap dancing her way to a future. Fortunately, her roommate, Molly, works at the Stardust and invites Nomi to see the show, where she meets Crystal Conners (Gina Gershon, in the Bette Davis role), with whom she immediately forms a love/hate relationship. Nomi soon learns what she must do to get ahead, and the rest of the film documents her cat-like crawl up the showgirl ladder of success. Directed by Paul Verhoeven, (Robocop, Basic Instinct, The Fourth Man), Showgirls was conceived as the first big-budget 'adult' film since 1977's Caligula, and the first such production to wear the NC-17 rating; its failure at the box-office discouraged further attempts at large-scale adult productions.", poster_url: "http://content8.flixster.com/movie/28/55/285598_det.jpg", potatometer: 17)

# Movie.create(title: "Troll 2", synopsis: "In this ultra-cheapo Italian knock-off a little boy tries to warn his family and friends that the evil trolls his late grandfather used to tell him about are real. Unfortunately, no one believes him and he and his sister are sent to the enigmatic town of Nilbog where nightmarish things begin to happen.", poster_url: "http://content6.flixster.com/movie/11/15/15/11151508_det.jpg", potatometer: 6)

# Movie.create(title: "Baby Geniuses", synopsis: "Dr. Elena Kinder (Kathleen Turner) is the highly visible chief executive of BABYCO, the world's largest manufacturer of baby products. The company funds orphanages across the world and just opened an indoor theme park for children adjacent to its corporate headquarters in Los Angeles. Unbeknownst to the public, Kinder, with the help of Dr. Heep (Christopher Lloyd), has been conducting a vast research program devoted to decrypting in secret labs deep beneath BABYCO's corporate campus the language that babies speak. It's said that Tibetans believe all babies are born with complete knowledge of the universe and the ability to speak to each other in an ancient language. However, once infants turn two years old, they lose this knowledge as they bond more closely with adults. To study this theory, Dr. Kinder has culled the smartest babies from her orphanages to be raised in a special development program in her private lab. As a test of developmental progress, she has separated a pair of twins, Sly and Witt. While Sly is raised within the lab, Witt has been adopted by Kinder's niece, Robin Bobbins (Kim Cattrall) and her husband Dan (Peter MacNicol), who run an old-fashioned day care and child research center. Sly manages to escape the center and finds his way to a shopping mall during Christmas. While eluding Kinder's henchmen, Sly stumbles across Witt; Witt is promptly mistaken for Sly and taken away, while Sly goes to the day care center with his new mother. The two boys, who develop an empathic link, must find each other and free the children from the research center before Dr. Kinder can smuggle them out of the country.", poster_url: "http://content7.flixster.com/movie/10/09/74/10097481_det.jpg", potatometer: 2)

# Movie.create(title: "From Justin to Kelly", synopsis: "From the producer and writer of Spice World and the director of She's All That comes this musical comedy inspired by and featuring the stars of Fox's hit reality show American Idol. Starring the winner and runner-up of the show's first season, Kelly Clarkson and Justin Guarini, as slightly fictionalized versions of themselves, From Justin to Kelly attempts to recreate the atmosphere of the fun-loving beach musicals of the 1960s. When Kelly (Clarkson) and Justin (Guarini) embark on a vacation in search of some fun in the sun with their respective groups of friends, the two meet and fall for each other at first sight. Unfortunately, a series of comedic mishaps and hijinks gets in the way of them getting together. Several song-and-dance numbers ensue. In addition to Clarkson and Guarini, the film stars Greg Siff, Brian Dietzen, and Katherine Bailess.", poster_url: "http://content7.flixster.com/movie/11/16/47/11164713_det.jpg", potatometer: 10)

# Movie.create(title: "Battlefield Earth", synopsis: "When an alien race called the Psyclos turns the Earth into a mining colony, it's up to rebel hero, Johnny Goodboy, to lead a revolt and save the planet from the giant alien species.", poster_url: "http://content6.flixster.com/movie/26/03/260312_det.jpg", potatometer: 3)
